chef/knife-tidy

knife-tidy.gemspec
Signed-off-by: EC2 Default User <ec2-user@ip-10-42-42-1.us-west-2.compute.internal>
=> removed bin from spec

Rakefile, lib/knife-tidy/version.rb
=> bump version to 0.1.1

conf/substitutions.json.example, lib/chef/knife/tidy_backup_clean.rb, lib/chef/knife/tidy_base.rb, lib/chef/tidy_acls.rb, lib/chef/tidy_common.rb, lib/chef/tidy_substitutions.rb
=> moved all common functions to tidy_common.rb

lib/knife-tidy/version.rb
=> bump version to 0.2.0

lib/chef/knife/tidy_server_report.rb
In the current implementation, we only check cookbook versions from the
`cookbook` node attribute on each node.  This adds a cross check against
all environment cookbook constraints to make sure we leave at least one
version of a cookbook to satisfy each constraint (assuming there is one
in the full cookbook list).
Signed-off-by: Nolan Davidson <ndavidson@chef.io>
=> Add environment checking for unused cookbook list

lib/chef/knife/tidy_backup_clean.rb, lib/chef/knife/tidy_server_report.rb, lib/knife-tidy/version.rb
=> release 0.2.1

knife-tidy.gemspec, lib/knife-tidy/version.rb
=> setting required ruby to >= 2.0.0

lib/chef/knife/tidy_backup_clean.rb, lib/chef/tidy_acls.rb
=> correct any cookbook metadata name issues

lib/knife-tidy/version.rb
=> bump patch to 0.2.4

lib/chef/knife/tidy_server_clean.rb
=> disable server clean

lib/chef/knife/tidy_server_clean.rb
=> added dry-run to server clean

lib/knife-tidy/version.rb
=> bump to 0.3.0

lib/chef/knife/tidy_backup_clean.rb
=> newline for action needed messages

lib/chef/knife/tidy_backup_clean.rb
=> generate a metadata.rb if needed

lib/chef/knife/tidy_backup_clean.rb
=> fixed name mismatch in metadata.json

lib/chef/knife/tidy_backup_clean.rb
=> fixing null values and emtpy arrays in metadata.json

lib/chef/tidy_common.rb, lib/chef/tidy_substitutions.rb
=> boiler plate gsub file now works

lib/chef/knife/tidy_backup_clean.rb
=> check if metadata.has_key?('platforms')

lib/chef/knife/tidy_server_report.rb
Signed-off-by: Nolan Davidson <ndavidson@chef.io>
=> Catch pins with no cookbooks

CHANGELOG.md, lib/knife-tidy/version.rb
=> bump to 0.3.5

lib/chef/knife/tidy_backup_clean.rb
=> first check if the_user.has_key?('email')

CHANGELOG.md, lib/knife-tidy/version.rb
=> bump to 0.3.6

lib/chef/knife/tidy_backup_clean.rb, lib/chef/tidy_common.rb
=> role run_list clean up and metadata name regex simplification

lib/chef/knife/tidy_backup_clean.rb
=> fix merge conflict from rebase

lib/chef/knife/tidy_backup_clean.rb
=> fix NilClass on env_run_lists

CHANGELOG.md, lib/knife-tidy/version.rb
=> bump to 0.4.0

CHANGELOG.md, lib/knife-tidy/version.rb
=> bump version to 0.4.1

lib/chef/knife/tidy_server_clean.rb
=> deleting nodes also deletes client

lib/chef/knife/tidy_server_clean.rb
=> better warning message before confirmation

README.md, lib/chef/knife/tidy_server_clean.rb
=> enabling deletion of stale nodes

CHANGELOG.md, lib/knife-tidy/version.rb
=> bump to 0.5.0

CHANGELOG.md, lib/knife-tidy/version.rb
=> bump patch to 0.5.1

lib/chef/knife/tidy_backup_clean.rb
=> fixing regex for whitespace

CHANGELOG.md, lib/knife-tidy/version.rb
=> bump to 0.5.2

lib/chef/knife/tidy_server_clean.rb
This fixes https://github.com/chef-customers/knife-tidy/issues/53
=> fixing orgs with underscores

CHANGELOG.md, lib/knife-tidy/version.rb
=> bump path to 0.6.1

lib/chef/knife/tidy_notify.rb
Signed-off-by: Josh Hudson <jhudson@chef.io>
=> Filter email notifications on org_list config option.

lib/chef/knife/tidy_backup_clean.rb, lib/chef/tidy_acls.rb
Signed-off-by: Josh Hudson <jhudson@chef.io>
=> Add admins/users groups to the read acl for clients from < CS 12.5

CHANGELOG.md, lib/knife-tidy/version.rb
=> release 0.7.0

lib/chef/tidy_acls.rb
Signed-off-by: Josh Hudson <jhudson@chef.io>
=> Fix validate_user_acls and default_user_acl methods

lib/knife-tidy/version.rb
=> bump to 1.2.0

.travis.yml
=> Add Ruby 2.2 and 2.5 testing in Travis

README.md
=> Add gem and travis badges to the readme

.github/CODEOWNERS, .github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
=> Add github templates and codeowners file

README.md
Signed-off-by: dheerajd-msys <dheeraj.dubey@msystechnologies.com>
- Update README for OSS Best Practices
- No need to update Github PR template
=> Update README for OSS Best Practices

Rakefile, knife-tidy.gemspec, lib/chef/knife/tidy_backup_clean.rb, lib/chef/knife/tidy_notify.rb, lib/chef/knife/tidy_server_clean.rb, lib/chef/knife/tidy_server_report.rb, lib/chef/tidy_acls.rb, lib/chef/tidy_common.rb, lib/chef/tidy_server.rb, lib/chef/tidy_substitutions.rb
=> Chefstyle fixes

Gemfile, lib/chef/knife/tidy_backup_clean.rb
=> Fix some test failures

lib/chef/knife/tidy_backup_clean.rb
Fixes https://github.com/chef/knife-tidy/issues/109
We'll load cookbooks individually now, by version. This eliminates the issue where multiple cookbooks were being merged during load.
Tested with an older and newest chefdk:
```
Chef Development Kit Version: 3.13.1
chef-client version: 14.14.29
delivery version: master (4b21ec7e07fdfa82e86aa80e4f2372dde8e368bb)
berks version: 7.0.8
kitchen version: 1.25.0
inspec version: 3.9.3
```
```
ChefDK version: 4.7.113
Chef Infra Client version: 15.8.23
Chef InSpec version: 4.18.85
Test Kitchen version: 2.3.4
Foodcritic version: 16.2.0
Cookstyle version: 5.21.9
```
=> fixes cookbook loading so that it works with newer chef client

README.md, lib/knife-tidy/version.rb
Minor version bump for https://github.com/chef/knife-tidy/pull/117
=> Fix README typo and bump minor version for new flag

README.md, lib/chef/knife/tidy_backup_clean.rb, lib/chef/knife/tidy_notify.rb, lib/chef/knife/tidy_server_report.rb, lib/chef/tidy_acls.rb
=> Fix minor spelling mistakes

.expeditor/config.yml, .expeditor/verify.pipeline.yml, .rubocop.yml, Gemfile, knife-tidy.gemspec
Add Ruby 2.3 testing and pin test deps to fix testing
=> Add Ruby 2.3/3.0 testing and pin test deps to fix testing

.github/CODEOWNERS
Signed-off-by: Vikram Karve <vikram.karve@progress.com>
This repo will be maintained by the Workstation/ Community Tools team. It currently has no active maintainer.
=> Update code owners to workstation/ tools team

lib/chef/knife/tidy_server_report.rb
Signed-off-by: Vikram Karve <vikram.karve@progress.com> on behalf of ECOTTOM [ECOTTOM@mitre.org](mailto:ECOTTOM@mitre.org)
Please refer https://github.com/chef/knife-tidy/pull/139
Creating separate PR as merge is not working for the original PR. The relevant changes are in only `lib/chef/knife/tidy_server_report.rb`
=> To merge changes from PR by ecottom

.expeditor/verify.pipeline.yml, knife-tidy.gemspec
Signed-off-by: Ashique P S <Ashique.saidalavi@progress.com>
Support for Ruby 3.1
Removed support for Ruby 2.6 and older versions
=> Support for Ruby 3.1 and removed EOL versions

.expeditor/verify.pipeline.yml, Gemfile, knife-tidy.gemspec
=> Updated ruby dependency and removed 2.7 ruby pipeline
